name: sgnify
channels:
  - pytorch
  - conda-forge
  - nvidia
  - fastai
  - conda-forge/label/cf202003
dependencies:
  - python==3.10.*
  - pip
  - git
  - configargparse
  - einops
  - opencv-python-headless
  - gdown
  - kornia
  - loguru
  - numpy
  - omegaconf
  - openh264
  - pyrender
  - pytorch
  - pytorch-cuda
  - pytorch3d::pytorch3d
  - scikit-learn
  - torchvision
  - tqdm
  - trimesh
  - yacs
  - pip:
    - -e ./spectre/external/face_alignment
    - -e ./spectre/external/face_detection
    - git+https://github.com/muelea/selfcontact
    - git+https://github.com/nghorbani/ViTPose
    - human-body-prior
    - importlib-resources
    - mediapipe
    - smplx
    - ultralytics
    - python-ffmpeg
    - networkx==2.5.1
